services:
  postgres:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_PASSWORD: "#Anku265482"
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: node-app
    command: node app.js
    ports:
      - "5000:5000"
    depends_on:
      - postgres